In [5]:
import numpy as np

In [99]:
l=[1,2,3,4]

In [100]:
ar=np.array(l)

In [101]:
ar

array([1, 2, 3, 4])

In [102]:
type(ar)

numpy.ndarray

In [103]:
np.array([[1,2],[2,4]])

array([[1, 2],
       [2, 4]])

In [104]:
np.asarray(l)

array([1, 2, 3, 4])

In [105]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [106]:
#
b=np.matrix(l)

In [107]:
b

matrix([[1, 2, 3, 4]])

In [108]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [109]:
a=np.array(l)

In [110]:
c=a

In [111]:
a

array([1, 2, 3, 4])

In [112]:
c

array([1, 2, 3, 4])

In [113]:
c[0]=100

In [114]:
c

array([100,   2,   3,   4])

In [115]:
a

array([100,   2,   3,   4])

In [116]:
d=np.copy(a)

In [117]:
a

array([100,   2,   3,   4])

In [118]:
d

array([100,   2,   3,   4])

In [119]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [6]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [7]:

u=iterable=(i*i for i in range(7))
u

<generator object <genexpr> at 0x00000264A53711C0>

In [8]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16, 25, 36])

In [215]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [9]:
np.fromstring('235 228',sep=' ')

array([235., 228.])

In [11]:
np.fromstring('mangesh bhosale',sep=' ')  

C:\Users\Admin\AppData\Local\Temp\ipykernel_3812\2049369665.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('mangesh bhosale',sep=' ')


array([], dtype=float64)

In [126]:
ar=np.array(l)

In [127]:
ar

array([1, 2, 3, 4])

In [128]:
ar.ndim

1

In [129]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [130]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
ar2.ndim

2

In [132]:
ar2.size

8

In [133]:
ar2.shape

(2, 4)

In [134]:
 ar2.dtype

dtype('int32')

In [138]:
ar22=np.array([(1.4,45,45),(45,26,58)])

In [139]:
ar22

array([[ 1.4, 45. , 45. ],
       [45. , 26. , 58. ]])

In [140]:
ar23=np.array([[1.4,45,45],[45,26,58]])


In [143]:
ar23.dtype

dtype('float64')

In [148]:
np.arange(2.3,8.6,.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7,
       4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3,
       7.5, 7.7, 7.9, 8.1, 8.3, 8.5])

In [149]:
list(np.arange(2.3,5.6,2))

[2.3, 4.3]

In [157]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [12]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [158]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [162]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [163]:
np.ones(4)


array([1., 1., 1., 1.])

In [164]:
on=np.ones((2,3,4))

In [165]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [166]:
on *4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [171]:
np.empty((3,4))

array([[1., 1., 1., 2.],
       [2., 2., 1., 2.],
       [1., 2., 1., 2.]])

In [176]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [182]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [14]:
np.logspace(2,4, 10,base=25)

array([   625.        ,   1278.0073532 ,   2613.28447172,   5343.67483336,
        10926.80916821,  22343.26794232,  45687.77715958,  93422.90425784,
       191032.25375763, 390625.        ])

In [18]:
arr=np.random.randn(3,4)

In [16]:
import pandas as pd

In [19]:
pd.DataFrame(arr)

0         1         2         3
0  0.678680  0.052466 -0.673218 -0.878263
1  0.183270  0.129489 -0.472098 -0.104159
2  0.687478 -0.129329 -1.393657 -1.272783

In [20]:
np.random.rand(3,4)

array([[0.84965272, 0.56481929, 0.76741071, 0.45664417],
       [0.94295787, 0.80264646, 0.05304111, 0.34838353],
       [0.90121019, 0.84826461, 0.84457086, 0.49122561]])

In [22]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [23]:
ad=pd.read_csv('test.csv')
ad

Unnamed: 0    0   1    2    3    4    5    6   7    8  ...  390  391  \
0             0   75  94  102   23   95  100  105   4   58  ...   31   47   
1             1   18  25   70   66   20   12   22  82   82  ...   40   25   
2             2  109  60   57   76    7   69   76   7  101  ...   81   66   
3             3   25  33   79   45   73   58   93  97   43  ...   28   86   
4             4   41  92   90   69   67   66   47  50   20  ...   37    3   
..          ...  ...  ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   
295         295    2  98   76   52    9   10   38  85   96  ...   55   45   
296         296   18  83   63  107   33   44   53  19   25  ...   46    7   
297         297   63  10   60   53   15  101   70   4   71  ...   93  108   
298         298   75  61    6   31   47   87   94  32   45  ...   22   86   
299         299   49  58   33   24  105   46   73  93   21  ...  105   16   

     392  393  394  395  396  397  398  399  
0      4  106   62   94   80   51    1   49  
1     33    5  105   31   49    7   25   24  
2    104   18   18   92   94   87   64   72  
3     88   95   83   87   48   14   18   45  
4     22   14  101   92   83   88   42   42  
..   ...  ...  ...  ...  ...  ...  ...  ...  
295   32   72  102   80   65    5   60    5  
296   40   98   58   76   82   10   17   68  
297   92   83    9   33   24   98  101   40  
298   87   19   49   24   31  103   17   97  
299   92   54   89   59   58   74   83   58  

[300 rows x 401 columns]

In [24]:
ar.reshape(1,4)

NameError: name 'ar' is not defined

In [217]:
arr.reshape(5,-12)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [ ]:
arr3[ arr, 50]

In [25]:
row=np.array([1,2,3,4])

In [26]:
row

array([1, 2, 3, 4])

In [27]:
arr=row

In [1]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,454,34,25,257])
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 454,  34,  25,
       257])

In [10]:
np.sort(arr)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  25,  34, 257,
       454])

In [13]:
np.searchsorted(arr,32)

10

In [26]:
arr1=np.array([32,25,0,85,9,9,6,35,6,56,72])
arr1

array([32, 25,  0, 85,  9,  9,  6, 35,  6, 56, 72])

In [27]:

np.count_nonzero(arr1)

10

In [28]:
np.where(arr1>5)

(array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [29]:
arr1.byteswap()

array([ 536870912,  419430400,          0, 1426063360,  150994944,
        150994944,  100663296,  587202560,  100663296,  939524096,
       1207959552])

In [32]:
np.extract(arr1>3,arr1)

array([32, 25, 85,  9,  9,  6, 35,  6, 56, 72])

In [33]:
a=np.copy(arr1)

In [34]:
a

array([32, 25,  0, 85,  9,  9,  6, 35,  6, 56, 72])

In [35]:
b=a.view()

In [36]:
b

array([32, 25,  0, 85,  9,  9,  6, 35,  6, 56, 72])

In [37]:
a[0]=100

In [38]:
a

array([100,  25,   0,  85,   9,   9,   6,  35,   6,  56,  72])

In [39]:
b

array([100,  25,   0,  85,   9,   9,   6,  35,   6,  56,  72])

In [42]:
import numpy.matlib as nm

In [43]:
nm.zeros((2,3))

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [44]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [55]:
arr1=np.random.randint(1,9,(3,3))
arr1

array([[3, 1, 2],
       [4, 6, 1],
       [5, 1, 5]])

In [56]:
arr2=np.random.randint(1,9,(3,4))
arr2

array([[8, 6, 3, 7],
       [8, 3, 1, 5],
       [3, 7, 2, 5]])

In [57]:
arr2.reshape(6,-45125)

array([[8, 6],
       [3, 7],
       [8, 3],
       [1, 5],
       [3, 7],
       [2, 5]])

In [58]:
arr2.reshape(2,6)

array([[8, 6, 3, 7, 8, 3],
       [1, 5, 3, 7, 2, 5]])

In [60]:
arr2.T

array([[8, 8, 3],
       [6, 3, 7],
       [3, 1, 2],
       [7, 5, 5]])

In [64]:
np.expand_dims(arr2,axis=2)

array([[[8],
        [6],
        [3],
        [7]],

       [[8],
        [3],
        [1],
        [5]],

       [[3],
        [7],
        [2],
        [5]]])

In [65]:
np.squeeze(arr2)

array([[8, 6, 3, 7],
       [8, 3, 1, 5],
       [3, 7, 2, 5]])

In [66]:
np.repeat(arr2,3)

array([8, 8, 8, 6, 6, 6, 3, 3, 3, 7, 7, 7, 8, 8, 8, 3, 3, 3, 1, 1, 1, 5,
       5, 5, 3, 3, 3, 7, 7, 7, 2, 2, 2, 5, 5, 5])

In [67]:
np.roll(arr2,2)

array([[2, 5, 8, 6],
       [3, 7, 8, 3],
       [1, 5, 3, 7]])

In [68]:
np.diag(arr)

array([[  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   5,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   6,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   7,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   8,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   9,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  10,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 454,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0, 

In [69]:
arr2

array([[8, 6, 3, 7],
       [8, 3, 1, 5],
       [3, 7, 2, 5]])

In [70]:
np.diag(arr2)

array([8, 3, 2])

In [76]:
d1=np.random.randint(1,7,(4,4))
d1
d2=np.random.randint(5,10,(4,4))
d2
d1

array([[2, 2, 3, 4],
       [1, 2, 5, 4],
       [6, 3, 5, 1],
       [3, 3, 4, 1]])

In [77]:
d2

array([[7, 8, 7, 9],
       [9, 6, 6, 7],
       [8, 9, 5, 5],
       [5, 9, 9, 9]])

In [75]:
d1+d2

array([[11, 12,  7,  9],
       [11,  9, 10,  8],
       [10,  6,  7, 10],
       [ 9, 13, 11,  8]])

In [78]:
d2-d1

array([[5, 6, 4, 5],
       [8, 4, 1, 3],
       [2, 6, 0, 4],
       [2, 6, 5, 8]])

In [79]:
d1*d2

array([[14, 16, 21, 36],
       [ 9, 12, 30, 28],
       [48, 27, 25,  5],
       [15, 27, 36,  9]])

In [80]:
d2/d1

array([[3.5       , 4.        , 2.33333333, 2.25      ],
       [9.        , 3.        , 1.2       , 1.75      ],
       [1.33333333, 3.        , 1.        , 5.        ],
       [1.66666667, 3.        , 2.25      , 9.        ]])

In [81]:
d2%d1

array([[1, 0, 1, 1],
       [0, 0, 1, 3],
       [2, 0, 0, 0],
       [2, 0, 1, 0]])

In [82]:
d2 **d1

array([[    49,     64,    343,   6561],
       [     9,     36,   7776,   2401],
       [262144,    729,   3125,      5],
       [   125,    729,   6561,      9]])

In [83]:
d2&d1

array([[2, 0, 3, 0],
       [1, 2, 4, 4],
       [0, 1, 5, 1],
       [1, 1, 0, 1]])

In [84]:
-d2

array([[-7, -8, -7, -9],
       [-9, -6, -6, -7],
       [-8, -9, -5, -5],
       [-5, -9, -9, -9]])

In [88]:
-d1

array([[-2, -2, -3, -4],
       [-1, -2, -5, -4],
       [-6, -3, -5, -1],
       [-3, -3, -4, -1]])

In [85]:
d1|d2

array([[ 7, 10,  7, 13],
       [ 9,  6,  7,  7],
       [14, 11,  5,  5],
       [ 7, 11, 13,  9]])

In [87]:
d1<d2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [89]:
s1=np.array(("mangesh",'bhosale'))

In [90]:
s1

array(['mangesh', 'bhosale'], dtype='<U7')

In [92]:
s1.dtype

dtype('<U7')

In [93]:
np.char.title(s1)

array(['Mangesh', 'Bhosale'], dtype='<U7')

In [94]:
np.char.capitalize(s1)

array(['Mangesh', 'Bhosale'], dtype='<U7')

In [95]:
#
m1=np.random.randint(1,7,(4,4))

In [96]:
m1

array([[4, 2, 3, 3],
       [4, 1, 4, 4],
       [5, 5, 6, 3],
       [2, 3, 5, 4]])

In [99]:
np.sin(m1)

array([[-0.7568025 ,  0.90929743,  0.14112001,  0.14112001],
       [-0.7568025 ,  0.84147098, -0.7568025 , -0.7568025 ],
       [-0.95892427, -0.95892427, -0.2794155 ,  0.14112001],
       [ 0.90929743,  0.14112001, -0.95892427, -0.7568025 ]])

In [98]:
np.tan(m1)

array([[ 1.15782128, -2.18503986, -0.14254654, -0.14254654],
       [ 1.15782128,  1.55740772,  1.15782128,  1.15782128],
       [-3.38051501, -3.38051501, -0.29100619, -0.14254654],
       [-2.18503986, -0.14254654, -3.38051501,  1.15782128]])

In [100]:
np.cos(m1)

array([[-0.65364362, -0.41614684, -0.9899925 , -0.9899925 ],
       [-0.65364362,  0.54030231, -0.65364362, -0.65364362],
       [ 0.28366219,  0.28366219,  0.96017029, -0.9899925 ],
       [-0.41614684, -0.9899925 ,  0.28366219, -0.65364362]])

In [102]:
np.power(m1,3)

array([[ 64,   8,  27,  27],
       [ 64,   1,  64,  64],
       [125, 125, 216,  27],
       [  8,  27, 125,  64]], dtype=int32)

In [103]:
np.min(m1)

1

In [104]:
np.max(m1)

6

In [105]:
np.std(m1)

1.2686114456365274

In [106]:
np.var(m1)

1.609375

In [107]:
np.median(m1)

4.0

In [108]:
np.sqrt(m1)

array([[2.        , 1.41421356, 1.73205081, 1.73205081],
       [2.        , 1.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.44948974, 1.73205081],
       [1.41421356, 1.73205081, 2.23606798, 2.        ]])

In [109]:
np.exp(m1)

array([[ 54.59815003,   7.3890561 ,  20.08553692,  20.08553692],
       [ 54.59815003,   2.71828183,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 403.42879349,  20.08553692],
       [  7.3890561 ,  20.08553692, 148.4131591 ,  54.59815003]])