In [98]:
import numpy as np

In [99]:
l=[1,2,3,4]

In [100]:
ar=np.array(l)

In [101]:
ar

array([1, 2, 3, 4])

In [102]:
type(ar)

numpy.ndarray

In [103]:
np.array([[1,2],[2,4]])

array([[1, 2],
       [2, 4]])

In [104]:
np.asarray(l)

array([1, 2, 3, 4])

In [105]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [106]:
#
b=np.matrix(l)

In [107]:
b

matrix([[1, 2, 3, 4]])

In [108]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [109]:
a=np.array(l)

In [110]:
c=a

In [111]:
a

array([1, 2, 3, 4])

In [112]:
c

array([1, 2, 3, 4])

In [113]:
c[0]=100

In [114]:
c

array([100,   2,   3,   4])

In [115]:
a

array([100,   2,   3,   4])

In [116]:
d=np.copy(a)

In [117]:
a

array([100,   2,   3,   4])

In [118]:
d

array([100,   2,   3,   4])

In [119]:
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [120]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [213]:
iterable=(i*i for i in range(7))

In [214]:
# np.fromiter(iterable,int)

In [215]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36.])

In [124]:
np.fromstring('235 228',sep=' ')

array([235., 228.])

In [125]:
np.fromstring('mangesh bhosale',sep=' ')  

C:\Users\Admin\AppData\Local\Temp\ipykernel_14152\2049369665.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('mangesh bhosale',sep=' ')


array([], dtype=float64)

In [126]:
ar=np.array(l)

In [127]:
ar

array([1, 2, 3, 4])

In [128]:
ar.ndim

1

In [129]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [130]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
ar2.ndim

2

In [132]:
ar2.size

8

In [133]:
ar2.shape

(2, 4)

In [134]:
 ar2.dtype

dtype('int32')

In [138]:
ar22=np.array([(1.4,45,45),(45,26,58)])

In [139]:
ar22

array([[ 1.4, 45. , 45. ],
       [45. , 26. , 58. ]])

In [140]:
ar23=np.array([[1.4,45,45],[45,26,58]])


In [143]:
ar23.dtype

dtype('float64')

In [148]:
np.arange(2.3,8.6,.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7,
       4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3,
       7.5, 7.7, 7.9, 8.1, 8.3, 8.5])

In [149]:
list(np.arange(2.3,5.6,2))

[2.3, 4.3]

In [157]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [158]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [162]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [163]:
np.ones(4)


array([1., 1., 1., 1.])

In [164]:
on=np.ones((2,3,4))

In [165]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [166]:
on *4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [171]:
np.empty((3,4))

array([[1., 1., 1., 2.],
       [2., 2., 1., 2.],
       [1., 2., 1., 2.]])

In [176]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [182]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [183]:
arr=np.random.randn(3,4)

In [184]:
import pandas as pd

In [185]:
pd.DataFrame(arr)

0         1         2         3
0  1.292139  0.179478 -0.964249  0.757969
1  0.334775 -1.340400  1.284577  0.665269
2 -1.479897 -0.753358 -0.456834 -0.318434

In [187]:
np.random.rand(3,4)

array([[0.51782566, 0.94029233, 0.71993395, 0.39240906],
       [0.56242237, 0.71561338, 0.23911614, 0.19962103],
       [0.84916506, 0.59010054, 0.28910347, 0.35144003]])

In [196]:
pd.DataFrame(np.random.randint(1,110,(3,4))).to_csv('test.csv')

In [198]:
ad=pd.read_csv('test.csv')
ad

Unnamed: 0   0   1   2    3
0           0  23  13   9   29
1           1  40  14  98  107
2           2  95   4  49   97

In [205]:
ar.reshape(1,4)

array([[1, 2, 3, 4]])

In [209]:
arr.reshape(1,-10)

array([[ 1.29213852,  0.17947837, -0.96424893,  0.75796851,  0.33477504,
        -1.34040013,  1.28457685,  0.66526913, -1.4798971 , -0.75335784,
        -0.4568339 , -0.31843364]])